osx_image: xcode8
language: objective-c

env:
  global:
    - LANG=en_US.UTF-8
    
  matrix:
    - PLATFORM="iOS"
    - PLATFORM="tvOS"
    - PLATFORM="macOS"

cache:
  - bundler

before_install:
  - brew update
  - carthage bootstrap --platform $PLATFORM

script:
  - bundle exec rake ci[$PLATFORM]

after_success:
  - bash <(curl -s https://codecov.io/bash)

